parameters:
#    amb_user.example.class: Amb\UserBundle\Example

services:
#    amb_user.example:
#        class: %amb_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
