<?php

namespace Amb\DebitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDepenseRepository extends EntityRepository
{
}
