<?php

namespace Amb\GlobalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalyRepository extends EntityRepository
{

	public function JournalTransaction($date_debut, $date_fin, $banque = null, $mot_cle = null , $adh = null, $mode = null ){
		$connection = $this->getEntityManager()->getConnection();
	    $sql = 'SELECT *  From mouvement
				WHERE ( mouvement.date_Operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\') ';
		if ($mot_cle != null) {
			$sql .= ' AND ( mouvement.piece LIKE \'%'.$mot_cle.'%\' OR mouvement.type LIKE \'%'.$mot_cle.'%\') ';
		}
		if ($adh != null) {
			$sql .= ' AND ( mouvement.adhesion = '.$adh.') ';
		}
		if ($banque != null) {
			$sql .= ' AND mouvement.banque_id = '.$banque.' ';
		}
		if ($mode != null) {
			$sql .= ' AND mouvement.mode LIKE \'%'.$mode.'%\' ';
		}
		$sql .= ' ORDER BY mouvement.date_Operation ASC';
	    return $connection->executeQuery($sql)->fetchAll();
	}

	public function SumMouvement($date_debut, $date_fin, $banque = null, $mot_cle = null, $adh = null, $mode = null ){
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT SUM(encaissement) as encaissements, SUM(depense) as depenses  From mouvement
				WHERE ( mouvement.date_Operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\') ';
		if ($mot_cle != null) {
			$sql .= ' AND ( mouvement.piece LIKE \'%'.$mot_cle.'%\' OR mouvement.type LIKE \'%'.$mot_cle.'%\') ';
		}
		if ($adh != null) {
			$sql .= ' AND ( mouvement.adhesion LIKE \'%'.$adh.'%\') ';
		}
		if ($banque != null) {
			$sql .= ' AND mouvement.banque_id = '.$banque.' ';
		}
		if ($mode != null) {
			$sql .= ' AND mouvement.mode LIKE \'%'.$mode.'%\' ';
		}
		return $connection->executeQuery($sql)->fetch();		
	}

	public function EncaissementDepenseParMois($annee = null){
		if (empty($annee)) {
			$annee=date("Y");
		}
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT
				      1 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=1 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=1
				UNION ALL
				SELECT
				      2 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=2 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=2
				UNION ALL
				SELECT
				      3 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=3 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=3
				UNION ALL
				SELECT
				      4 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=4 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=5
				UNION ALL
				SELECT
				      5 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=5 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=5
				UNION ALL
				SELECT
				      6 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=6 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=6
				UNION ALL
				SELECT
				      7 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=7 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=7
				UNION ALL
				SELECT
				      8 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=8 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=8
				UNION ALL
				SELECT
				      9 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=9 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=9
				UNION ALL
				SELECT
				      10 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=10 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=10
				UNION ALL
				SELECT
				      11 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=11 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=11
				UNION ALL
				SELECT
				      12 as mois,
				      sum(montant)         AS encaiss,
				      (select sum(montant) from depense where month(date_operation)=12 AND year(date_Operation) = '.$annee.') as depense
				      FROM encaissement WHERE statut = "valid" AND year(date_Operation) = '.$annee.' AND month(date_Operation)=12 ';
		
		return $connection->executeQuery($sql)->fetchAll();		
	}

	public function EncaissementParMois($annee = null){
		if (empty($annee)) {
			$annee=date("Y");
		}
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT
		    1 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=1 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=1 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=1 GROUP BY mois 
		UNION ALL
		SELECT
		    2 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=2 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=2 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=2 GROUP BY mois 
		UNION ALL
		SELECT
		    3 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=3 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=3 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=3 GROUP BY mois 
		UNION ALL
		SELECT
		    4 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=4 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=4 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=4 GROUP BY mois 
		UNION ALL
		SELECT
		    5 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=5 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=5 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=5 GROUP BY mois 
		UNION ALL
		SELECT
		    6 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=6 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=6 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=6 GROUP BY mois 
		UNION ALL
		SELECT
		    7 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=7 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=7 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=7 GROUP BY mois 
		UNION ALL
		SELECT
		    8 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=8 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=8 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=8 GROUP BY mois 
		UNION ALL
		SELECT
		    9 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=9 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=9 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=9 GROUP BY mois 
		UNION ALL
		SELECT
		    10 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=10 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=10 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=10 GROUP BY mois 
		UNION ALL
		SELECT
		    11 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=11 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=11 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=11 GROUP BY mois 
		UNION ALL
		SELECT
		    12 as mois,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="valid" AND month(date_Operation)=12 AND year(date_Operation) = '.$annee.'),0) as valid,
		    IFNULL((select sum(montant) from list_encaissement_current_adh where statut="invalid" AND month(date_Operation)=12 AND year(date_Operation) = '.$annee.'),0) as invalid
		    FROM list_encaissement_current_adh WHERE year(date_Operation) = '.$annee.' AND month(date_Operation)=12 GROUP BY mois 
		';
		
		return $connection->executeQuery($sql)->fetchAll();		
	}

	public function SumSituationApparts(){
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT  SUM(cout_global) as cout_global, 
						SUM(versement) as versement,  
						SUM(invalid) as invalid,  
						SUM(solde) as solde,  
						coalesce(SUM(impayee), 0) as impayee,
						count(*) as nbr  FROM situation_appt';
		
		return $connection->executeQuery($sql)->fetch();		
	}

	public function AppartsParCout(){
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT  SUM(cout_global) as cout_global, 
						SUM(surface_appt) as surface_appt, 
						SUM(surface_terrace) as surface_terrace, 
						SUM(surface_jardin) as surface_jardin,
						count(*) as nbr,  
						cout
						FROM situation_appt GROUP BY cout ORDER BY cout ASC';
		
		return $connection->executeQuery($sql)->fetchALL();		
	}

	public function AppartsLibreParCout(){
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT  SUM(surface_appt) as surface_appt, 
						SUM(surface_terrace) as surface_terrace, 
						SUM(surface_jardin) as surface_jardin, 
						count(*) as nbr,  
						cout
						FROM adhesion WHERE adherent_id is null GROUP BY cout ORDER BY cout ASC';
		
		return $connection->executeQuery($sql)->fetchALL();		
	}

	public function SumSituationConvention(){
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT  (SELECT SUM(montant) FROM depense WHERE contrat_id=contrat.id) as reglement,
						SUM(montant) as montant  FROM contrat WHERE date_resiliation is null';
		
		return $connection->executeQuery($sql)->fetch();		
	}

	public function SituationConventions(){
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT  *, 
				(SELECT raison_social FROM fournisseur WHERE id=contrat.fournisseur_id) as fournisseur,
				(SELECT SUM(montant) FROM depense WHERE contrat_id=contrat.id) as reglement
				FROM contrat WHERE date_resiliation is null';
		
		return $connection->executeQuery($sql)->fetchAll();		
	}

	public function RecetteCompteGestion($date_debut = null, $date_fin = null){
		$connection = $this->getEntityManager()->getConnection();
		if ($date_debut == null && $date_fin == null) {
			$date_debut = new \Datetime('01-01-'.date('Y'));
			$date_fin = new \Datetime('31-12-'.date('Y'));
		}
		$sql = 'SELECT type, SUM(montant) as montant FROM fg_da_active 
				WHERE date_Operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\'
				GROUP BY type';	
		
		
		
		return $connection->executeQuery($sql)->fetchAll();		
	}

	public function TotalRecetteCompteGestion($date_debut = null, $date_fin = null){
		$connection = $this->getEntityManager()->getConnection();
		if ($date_debut == null && $date_fin == null) {
			$date_debut = new \Datetime('01-01-'.date('Y'));
			$date_fin = new \Datetime('31-12-'.date('Y'));
		}
		$sql = 'SELECT SUM(montant) as total FROM fg_da_active 
				WHERE  date_Operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\'';
		
		
		return $connection->executeQuery($sql)->fetch();		
	}

	public function TotalRecetteCGDivers($date_debut = null, $date_fin = null){
		$connection = $this->getEntityManager()->getConnection();
		if ($date_debut == null && $date_fin == null) {
			$date_debut = new \Datetime('01-01-'.date('Y'));
			$date_fin = new \Datetime('31-12-'.date('Y'));
		}
		$sql = 'SELECT SUM(montant) as total FROM encaissement 
				WHERE  source is not null 
				AND compte="GESTION"
				AND date_Operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\'';
		
		
		return $connection->executeQuery($sql)->fetch();		
	}

	public function TotalRecetteAMDivers($date_debut = null, $date_fin = null){
		$connection = $this->getEntityManager()->getConnection();
		if ($date_debut == null && $date_fin == null) {
			$date_debut = new \Datetime('01-01-'.date('Y'));
			$date_fin = new \Datetime('31-12-'.date('Y'));
		}
		$sql = 'SELECT SUM(montant) as total FROM encaissement 
				WHERE  source is not null 
				AND compte="AMORTISSEMENT"
				AND date_Operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\'';
		
		
		return $connection->executeQuery($sql)->fetch();		
	}

	public function RecetteAmmor($date_debut = null, $date_fin = null){
		$connection = $this->getEntityManager()->getConnection();
		if ($date_debut == null && $date_fin == null) {
			$date_debut = new \Datetime('01-01-'.date('Y'));
			$date_fin = new \Datetime('31-12-'.date('Y'));
		}
		$sql = 'SELECT type_encaissment, SUM(montant) as montant FROM encaissement 
				WHERE type_encaissment="VERSEMENT" 
					AND statut="valid" 
					AND date_Operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\'
				GROUP BY type_encaissment';
		return $connection->executeQuery($sql)->fetchAll();		
	}

	public function TotalRecetteAmmor($date_debut = null, $date_fin = null){
		$connection = $this->getEntityManager()->getConnection();
		if ($date_debut == null && $date_fin == null) {
			$date_debut = new \Datetime('01-01-'.date('Y'));
			$date_fin = new \Datetime('31-12-'.date('Y'));
		}
		$sql = 'SELECT SUM(montant) as total FROM versements 
				WHERE date_Operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\'';
		
		return $connection->executeQuery($sql)->fetch();		
	}

	public function TotalResteDesistement(){
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT SUM(reste) as total FROM situation_desist ';
		
		return $connection->executeQuery($sql)->fetch();		
	}

	public function TotalRestitution(){
		$connection = $this->getEntityManager()->getConnection();
		$sql = 'SELECT SUM(montant) as total FROM depense
				WHERE adherent_id is not null
					AND adherent_id is not null 
					AND adhesion_id is not null 
					AND matricule is not null
					AND desistement_id is null ';
		
		return $connection->executeQuery($sql)->fetch();		
	}

	public function TotalDepense($type, $date_debut = null, $date_fin = null){
		$connection = $this->getEntityManager()->getConnection();
		if ($date_debut == null && $date_fin == null) {
			$date_debut = new \Datetime('01-01-'.date('Y'));
			$date_fin = new \Datetime('31-12-'.date('Y'));
		}
		if($type=='GESTION'){
			$sql = 'SELECT SUM(d.montant) as total FROM depense d
				WHERE ((SELECT t.compte FROM typedepense t WHERE t.id = d.typedepense_id) = "'.$type.'" 
				OR caisse is not null )
				AND date_operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\'';
		}else{
			$sql = 'SELECT SUM(d.montant) as total FROM depense d
				WHERE (SELECT t.compte FROM typedepense t WHERE t.id = d.typedepense_id) = "'.$type.'"
				AND date_operation BETWEEN \''.$date_debut->format('Y-m-d').'\' AND \''.$date_fin->format('Y-m-d').'\'';
		}
		return $connection->executeQuery($sql)->fetch();		
	}


}