<?php

namespace Amb\GlobalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScannRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScannRepository extends EntityRepository
{
	public function ListScann($type){
		$qb = $this->createQueryBuilder('s');
		$qb->add('select', 's ')
		   ->add('from', 'AmbGlobalBundle:Scann s');
	    //$qb->setParameters(array('statut' => 'valid'));
		if($type == 'adhs'){
			$qb->where('s.adherent is not null');
		}else{
			$qb->where('s.fournisseur is not null');
		}
	    return $qb;				
	}
}
