<?php

namespace Amb\CreditBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuitanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuitanceRepository extends EntityRepository
{
}
