parameters:
#    amb_adherent.example.class: Amb\AdherentBundle\Example

services:
    amb_adherent.coutglobal:
        class: Amb\AdherentBundle\Coutappt\CoutAppt
        tags:
            -  { name: twig.extension }
#    amb_adherent.example:
#        class: %amb_adherent.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
