<?php

namespace Amb\TraceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TraceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraceRepository extends EntityRepository
{
	public function Traceability($route, $action, $description, $element_id, $value, $entity, $deleted = null)
    {
    	$trace = new Trace;
    	$session = $this->getRequest()->getSession();
    	$repository = $this->getDoctrine()
                           ->getManager()
                           ->getRepository('AmbAdherentBundle:Adherent');
        $user = $repository->findOneBy(array('id' => $session>get('user_id')));


        $trace->setRoute($route);
        $trace->setAction($action);
        $trace->setDescription($description);
        $trace->setElementId($element_id);
        $trace->setValue($value);
        $trace->setEntity($entity);
        $trace->setDeleted($deleted);
        $trace->setUser($user);

        $em = $this->getDoctrine()->getEntityManager();
        $em->persist($trace);
        $em->flush();

    }
}
